name: quality-assurance
on: [push]
jobs:

  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version:
          - '~1.15.0'
          - '~1.16.0'
          - '~1.17.0'
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '${{ matrix.go_version }}'
      - uses: actions/checkout@v2

      - run: go vet ./...
      - run: go test -v -race ./...

  gofmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '~1.17.0'
      - uses: actions/checkout@v2

      - run: gofmt -w -s .
      - run: git diff --exit-code
